language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  # test with nose2: pyfakefs is not compatible with nose 1.3.7.
  # I experienced a test failure related to namespace packages:
  #    RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>
  # I could only remove the problem by switching to nose2 (even though I still
  # dislike its configuration bloat).
  - pip install --upgrade nose2

script:
  - nose2

